### ISSUE TITLE
Hashing order?

### ISSUE THREAD

**Issue by onalant** [onalant/privileged_residues#5]
We do not have a fixed hashing order. Example from `privileged_residues/bidentify.py+126`:
```
pairs_of_rays += [(next_n, c_ray), (c_ray, next_n)]
```

@weitzner

**Comment by weitzner** [comment]
We should probably have a consistent order.

**Comment by onalant** [comment]
✔️ ✔️

**Comment by onalant** [comment]
One issue: how do we represent fixed ray order for Sc_Sc interactions? This is especially problematic if we have more than one of donor-donor, donor-acceptor, or acceptor-acceptor in the same sidechain.

**Comment by weitzner** [comment]
They _should_ be mirror images of one another, but if not we can do both for those interactions. Testing will reveal the best path!
